server:
  port: 8080
  shutdown: graceful

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
    redis:
      host: localhost
      port: 6379

jwt:
    secret-key: ${SECRET_KEY}
    access-exp: ${ACCESS_EXP:1800}
    refresh-exp: ${REFRESH_EXP:1800}
