server:
  port: 8080
  shutdown: graceful

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:blog}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: sa # ${MYSQL_USERNAME:sa}
    password: password!1 # ${MYSQL_PASSWORD:password!1}
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect # org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
    redis:
      host: localhost
      port: 6379

  security:
    secret-key: ${SECRET_KEY:c2NyZXQK}
    access-exp: ${ACCESS_EXP:181}
    refresh-exp: ${REFRESH_EXP:180}
